# Generated by Django 3.0.6 on 2020-05-20 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('client_number', models.CharField(max_length=13)),
                ('client_e_mail', models.EmailField(max_length=254)),
                ('socials', models.URLField()),
                ('address', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manufacturer_number', models.CharField(max_length=13)),
                ('manufacturer_address', models.CharField(max_length=50)),
                ('manufacturer_site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('fabric', models.CharField(max_length=50)),
                ('manufacturer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.FloatField()),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('ordered_product', models.ManyToManyField(to='app.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
